<?php

/**
 * @file
 * The module for the Homepage callback and related content.
 */

/**
 *	Implements hook_menu()
 */
function canyon_home_page_menu() {

	$items = array();

	// Home Page`
	$items['homepage'] = array(
		'title' => 'Homepage',
		'page callback' => 'canyon_home_page',
		'file' => 'canyon_home_page.inc',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);

	return $items;

}
