<?php

/**
 * @file
 * The module for the Aboutpage callback and related content.
 */

/**
 *	Implements hook_menu()
 */
function canyon_about_page_menu() {

	$items = array();

	// About Page`
	$items['about'] = array(
		'title' => 'Aboutpage',
		'page callback' => 'canyon_about_page',
		'file' => 'canyon_about_page.inc',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);

	return $items;

}
